leftnav:
- identifier: 3edca454-764e-40e4-a81b-0504c739b7f5
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: d37b3aa2-ff0c-4286-b7ce-b7e4f3fbb2ea
  name: Lecture Notes and Readings
  url: /pages/lecture-notes-and-readings
  weight: 20
- identifier: 0215a2ad-e1ed-486b-9f33-ffbff29820d5
  name: Problem Sets
  url: /pages/problem-sets
  weight: 30
- identifier: 9e6d55e9-af4f-46c6-b699-b56c1d6ec403
  name: Two by Two Matrix Jacobians
  url: /pages/two-by-two-matrix-jacobians
  weight: 40
